language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_b4a69ec2b616_key -iv $encrypted_b4a69ec2b616_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cloud_user@3.135.246.229 pwd
script:
- sudo ocker build -t imthekrish/deploy-hapi-hello-world
- sudo docker run --name deploy-hapi-hello-world -p 80:3000 -d imthekrish/deploy-hapi-hello-world
