sudo: required
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_858f671823b3_key -iv $encrypted_858f671823b3_iv
  -in deploy_key.enc -out ./deploy_key -d
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t deploy-hapi-hello-world .
- docker run -d --name app deploy-hapi-hello-world
- docker ps -a
script:
- npm test
- docker tag deploy-hapi-hello-world:latest $DOCKER_USERNAME/deploy-hapi-hello-world:production
- docker push $DOCKER_USERNAME/deploy-hapi-hello-world:production
after_script:
- docker rm -f app
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    -o ConnectTimeout=300 -i deploy_key docker@18.191.25.182 './deploy.sh'
  on:
    branch: docker-user-branch
