nguage: node_js
node_js:
- stable
cache:
  directories:
  - node_modules

services:
- docker

before_install:
- docker build -t imthekrish/deploy-hapi-hello-world .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push imthekrish/deploy-hapi-hello-world
- openssl aes-256-cbc -K $encrypted_b4a69ec2b616_key -iv $encrypted_b4a69ec2b616_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -t -i ./deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=300 cloud_user@18.219.94.243 docker run --name deploy-hapi-hello-world -p 80:3000 -d imthekrish/deploy-hapi-hello-world; docker ps; docker images -a
script:
 - npm test
